In [4]:
import numpy as np

#Exercise 1
# Create a numpy array with numbers from 1 to 10
arr = np.arange(1, 11)

# Reshape the array to a 2x5 matrix
reshaped_arr = arr.reshape(2, 5)

print(reshaped_arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [6]:
#Exercise 2

# Create a numpy array with numbers from 1 to 20
arr = np.arange(1, 21)

# Extract the elements between the 5th and 15th index (excluding the 15th index)
extracted_elements = arr[5:15]

print(extracted_elements)

[ 6  7  8  9 10 11 12 13 14 15]


In [8]:
#Exercise 3

import pandas as pd

# Create a Pandas Series with the given data
data = {'apples': 3, 'bananas': 2, 'oranges': 1}
series = pd.Series(data)

# Add a new item with key 'pears' and value 4
series['pears'] = 4

print(series)

apples     3
bananas    2
oranges    1
pears      4
dtype: int64


In [10]:
#Exercise 4

import pandas as pd

# Create a dictionary with sample data for the dataframe
data = {
    'name': ['Anu', 'Akhi', 'Dachu', 'Akhil', 'Daksha', 'Kannan', 'Kukku', 'Priyanka', 'Nethan', 'Amruth'],
    'age': [25, 30, 35, 40, 22, 28, 33, 45, 50, 29],
    'gender': ['Female', 'Male', 'Female', 'Male', 'Female', 'Male', 'Female', 'Female', 'Male', 'Male']
}

# Create the dataframe
df = pd.DataFrame(data)

# Display the dataframe
print(df)

       name  age  gender
0       Anu   25  Female
1      Akhi   30    Male
2     Dachu   35  Female
3     Akhil   40    Male
4    Daksha   22  Female
5    Kannan   28    Male
6     Kukku   33  Female
7  Priyanka   45  Female
8    Nethan   50    Male
9    Amruth   29    Male


In [16]:
#Exercise 5

import pandas as pd

# Create the original dataframe (from previous question)
data = {
   'name': ['Anu', 'Akhi', 'Dachu', 'Akhil', 'Daksha', 'Kannan', 'Kukku', 'Priyanka', 'Nethan', 'Amruth'],
    'age': [25, 30, 35, 40, 22, 28, 33, 45, 50, 29],
    'gender': ['Female', 'Male', 'Female', 'Male', 'Female', 'Male', 'Female', 'Female', 'Male', 'Male']  
}

df = pd.DataFrame(data)

# Add the new 'occupation' column with corresponding values
df['occupation'] = ['Programmer', 'Manager', 'Analyst', 'Programmer', 'Manager', 
                     'Analyst', 'Programmer', 'Manager', 'Analyst', 'Programmer']

# Display the updated dataframe
print(df)


       name  age  gender  occupation
0       Anu   25  Female  Programmer
1      Akhi   30    Male     Manager
2     Dachu   35  Female     Analyst
3     Akhil   40    Male  Programmer
4    Daksha   22  Female     Manager
5    Kannan   28    Male     Analyst
6     Kukku   33  Female  Programmer
7  Priyanka   45  Female     Manager
8    Nethan   50    Male     Analyst
9    Amruth   29    Male  Programmer


In [20]:
#Exercise 6

# Select rows where age is greater than or equal to 30
df_age_30 = df[df['age'] >= 30]
print(df_age_30)

       name  age  gender  occupation
1      Akhi   30    Male     Manager
2     Dachu   35  Female     Analyst
3     Akhil   40    Male  Programmer
6     Kukku   33  Female  Programmer
7  Priyanka   45  Female     Manager
8    Nethan   50    Male     Analyst


In [22]:
#Exercise 7

# Convert the DataFrame to a CSV file
df.to_csv('data.csv', index=False)

# Read the CSV file back
df_from_csv = pd.read_csv('data.csv')
print(df_from_csv)

       name  age  gender  occupation
0       Anu   25  Female  Programmer
1      Akhi   30    Male     Manager
2     Dachu   35  Female     Analyst
3     Akhil   40    Male  Programmer
4    Daksha   22  Female     Manager
5    Kannan   28    Male     Analyst
6     Kukku   33  Female  Programmer
7  Priyanka   45  Female     Manager
8    Nethan   50    Male     Analyst
9    Amruth   29    Male  Programmer
